### ISSUE TITLE
Use a cookie to track alerts. By default only previously unseen alerts should be displayed.

### ISSUE THREAD

**Issue by binxboll** [jbccollins/metro-monitor#42]

**Comment by jbccollins** [comment]
Closing as users can now permanently dismiss alerts

**Comment by binxboll** [comment]
But how can I now view previously dismissed alerts?

**Comment by jbccollins** [comment]
I can add a button in the settings menu to make that happen. It's just `localStorage.clear()` in the dev console if you want to manually check how that would behave.
